[package]
name = "enet-mqtt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.2"
clap = "3.0.0-beta.4"
color-eyre = "0.5.11"
enet-client = "0.2.0"
eventuals = "0.6.6"
futures = "0.3.17"
lazy_static = "1.4.0"
matchit = "0.4.3"
paho-mqtt = { version = "0.9.1", features = ["vendored-ssl"] }
serde = "1.0.130"
serde_json = "1.0.68"
tokio = { version = "1.12.0", features = ["full"] }
tracing = "0.1.28"
tracing-subscriber = "0.2.25"

# enet-client = { version = "0.2.0", path = "../enet-rs/crates/client" }

[dev-dependencies]
serde_test = "1.0.130"

[profile.release]
lto = true
