[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.i686-unknown-linux-musl]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.i686-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
