name: release-please

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/workflows/upload-binaries.yml
        with:
          release: ${{ steps.release.outputs.tag_name }}
