name: Upload release binaries

on:
  workflow_call:
    inputs:
      release:
        description: GitHub release
        required: true
        type: string

  # TODO: remove
  workflow_dispatch:
    inputs:
      release:
        description: GitHub release
        required: true
        type: string

jobs:
  release:
    name: Create and upload binaries to GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: earthly/actions/setup-earthly@v1
      - run: earthly --version
      - run: earthly +all
