name: Upload release binaries

on:
  workflow_call:
    inputs:
      release:
        description: GitHub release
        required: true
        type: string

  # TODO: remove
  workflow_dispatch:
    inputs:
      release:
        description: GitHub release
        required: true
        type: string

jobs:
  release:
    name: Create and upload binaries to GitHub release
    runs-on: ubuntu-latest
    steps:
      - id: tag
        run: |
          TAG_NAME="${{ inputs.release }}"
          if [[ -z "$TAG_NAME" ]]; then
            TAG_NAME="${{ github.event.inputs }}"
          fi
          echo tag=$TAG_NAME
          echo ::set-output name=tag::$TAG_NAME
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: earthly/actions/setup-earthly@v1
      - run: earthly --version

      - name: Docker login
        if: github.ref == 'refs/heads/main' && github.repository == 'YoloDev/enet-mqtt'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: earthly --ci --push --remote-cache=ghcr.io/yolodev/enet-mqtt:build-cache +all
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ steps.tag.outputs.tag }}
          file_glob: true
